from driverConstants import *
from driverExplicit import ExplicitAnalysis
import driverUtils, sys
options = {
    'SIMExt':'.sim',
    'aba_timing':1,
    'ams':OFF,
    'analysisType':EXPLICIT,
    'applicationName':'analysis',
    'aqua':OFF,
    'beamSectGen':OFF,
    'biorid':OFF,
    'cavityTypes':[],
    'cavparallel':OFF,
    'compile_fortran':['ifort', '-V', '-c', '-fpp', '-fPIC', '-extend-source', '-DABQ_LNX86_64', '-DABQ_FORTRAN', '-auto', '-pc64', '-align', 'array64byte', '-prec-div', '-prec-sqrt', '-fp-model', 'precise', '-fimf-arch-consistency=true', '-mP2OPT_hpo_vec_divbyzero=F', '-no-fma', '-fp-speculation=safe', '-fprotect-parens', '-fstack-protector-strong', '-reentrancy', 'threaded', '-msse3', '-axcore-avx2,avx', '-WB', '-I.', '-DDPX', '-I/appl/soft/eng/simulia/EstProducts/2023', '-I/appl/soft/eng/simulia/EstProducts/2023/linux_a64/code/include', '-I/appl/soft/eng/simulia/EstProducts/2023/linux_a64/../SMAUsubs/PublicInterfaces', '-I/appl/soft/eng/simulia/EstProducts/2023/linux_a64/code/bin/SMAExternal/pmpi/include', '-I/scratch/project_2004956/test_VUMAT_ML', '-I/projappl/project_2004956/fortran-tf-lib/fortran-tf-lib/tf_intel/include/fortran-tf'],
    'complexFrequency':OFF,
    'contact':OFF,
    'cosimulation':OFF,
    'coupledProcedure':OFF,
    'cpus':1,
    'cse':OFF,
    'cyclicSymmetryModel':OFF,
    'directCyclic':OFF,
    'domains':1,
    'double_precision':BOTH,
    'dsa':OFF,
    'dynStepSenseAdj':OFF,
    'dynamic':OFF,
    'excite':OFF,
    'externalField':OFF,
    'externalFieldCSEAux':OFF,
    'externalFieldExtList':['.sim', '.SMAManifest'],
    'externalFieldFiles':[],
    'externalFieldSimReader':None,
    'fieldImport':OFF,
    'filPrt':[],
    'fils':[],
    'finitesliding':OFF,
    'flexiblebody':OFF,
    'foundation':OFF,
    'freqSimReq':OFF,
    'geostatic':OFF,
    'heatTransfer':OFF,
    'impJobExpVars':{},
    'importJobList':[],
    'importSim':OFF,
    'importer':OFF,
    'importerParts':OFF,
    'includes':[],
    'initialConditionsFile':OFF,
    'input':'uniaxial_tension_vumat',
    'inputFormat':INP,
    'interactive':None,
    'interpolExtList':['.odb', '.sim', '.SMAManifest'],
    'job':'uniaxial_tension_vumat',
    'keyword_licenses':[],
    'lanczos':OFF,
    'libs':[],
    'link_sl':['ifort', '-V', '-cxxlib', '-fPIC', '-threads', '-shared', '-Wl,--add-needed', '-Wl,-u,vcosimulation_', '-Wl,-u,vcosimulation0_', '-Wl,-u,vdflux_', '-Wl,-u,vdisp_', '-Wl,-u,vdload_', '-Wl,-u,vexternaldb_', '-Wl,-u,vfabric_', '-Wl,-u,vfric_', '-Wl,-u,vfric_coef_', '-Wl,-u,vfriction_', '-Wl,-u,vhetval_', '-Wl,-u,vsdvini_', '-Wl,-u,vuamp_', '-Wl,-u,vuanisohyper_inv_', '-Wl,-u,vuanisohyper_strain_', '-Wl,-u,vucharlength_', '-Wl,-u,vucreepnetwork_', '-Wl,-u,vuel_', '-Wl,-u,vueos_', '-Wl,-u,vueulgenprop_', '-Wl,-u,vuexpan_', '-Wl,-u,vufield_', '-Wl,-u,vufluidexch_', '-Wl,-u,vufluidexcheffarea_', '-Wl,-u,vugens_', '-Wl,-u,vuhard_', '-Wl,-u,vuinflprop_', '-Wl,-u,vuinter_', '-Wl,-u,vuinter_cza_', '-Wl,-u,vuinteraction_', '-Wl,-u,vumat_', '-Wl,-u,vumatht_', '-Wl,-u,vumullins_', '-Wl,-u,vuporepress_', '-Wl,-u,vusdfld_', '-Wl,-u,vusdfld_cza_', '-Wl,-u,vusuperelashardmod_', '-Wl,-u,vusuperelasplastmod_', '-Wl,-u,vutrs_', '-Wl,-u,vutrsnetwork_', '-Wl,-u,vuviscosity_', '-Wl,-u,vwave_', '-Wl,-u,_Z19SMAUXpU_XP_finalizeRi', '-Wl,-u,_Z21SMAUXpU_XP_initializeRi', '-Wl,-u,_Z23SMAUXpUsubs_XP_finalizeRi', '-Wl,-u,_Z25SMAUXpUsubs_XP_initializeRi', '-Wl,-u,_Z32SMAUXpUsubs_XP_specific_finalizeRi', '-Wl,-u,_Z34SMAUXpUsubs_XP_specific_initializeRi', '-Wl,-u,xplu_callallutils_', '-Wl,-soname,libexplicitU-D.so', '-L/scratch/project_2004956/test_VUMAT_ML', '-L/projappl/project_2004956/fortran-tf-lib/fortran-tf-lib/tensorflow/lib', '-L/projappl/project_2004956/fortran-tf-lib/fortran-tf-lib/tf_intel/lib64', '-lfortran-tf', '/scratch/project_2004956/test_VUMAT_ML/ml_module.o', '-lml_module', '-o', 'libexplicitU-D.so', 'code_binh.o', '/appl/soft/eng/simulia/EstProducts/2023/linux_a64/code/lib/libexplicitU-D_static.a', '-L/appl/soft/eng/simulia/EstProducts/2023/linux_a64/code/bin', '-lABQSMAShaShared-D', '-lABQSMAAncAdbModule', '-lABQSMAAspSupport', '-lABQSMAUsubsLib', '-L/appl/soft/eng/simulia/EstProducts/2023/linux_a64/code/bin/SMAExternal/pmpi/lib/linux_amd64', '-lABQDMP_Core', '-lABQMPI_api', '-lmpiCC', '-lABQSMAAbuBasicUtils', '-lexplicitB-D', '-lABQSMABasCoreUtils', '-lABQSMAEliLicenseModule', '-parallel', '-Wl,-Bdynamic', '-shared-intel'],
    'magnetostatic':OFF,
    'massDiffusion':OFF,
    'materialresponse':OFF,
    'modifiedTet':OFF,
    'moldflowFiles':[],
    'moldflowMaterial':OFF,
    'mp_mode':THREADS,
    'multiphysics':OFF,
    'noDmpDirect':[],
    'noMultiHost':[],
    'noMultiHostElemLoop':[],
    'noStdParallel':[],
    'no_domain_check':1,
    'onestepinverse':OFF,
    'outputKeywords':ON,
    'output_precision':FULL,
    'parallel_odb':SINGLE,
    'parallel_restartfile':SINGLE,
    'parameterized':OFF,
    'partsAndAssemblies':OFF,
    'parval':OFF,
    'pgdHeatTransfer':OFF,
    'postOutput':OFF,
    'preDecomposition':ON,
    'restart':OFF,
    'restartEndStep':OFF,
    'restartIncrement':0,
    'restartStep':0,
    'restartWrite':ON,
    'rezone':OFF,
    'runCalculator':OFF,
    'simPack':OFF,
    'soils':OFF,
    'soliter':OFF,
    'solverTypes':['DIRECT'],
    'ssd':OFF,
    'ssdCheckOK':False,
    'staticNonlinear':OFF,
    'steadyStateTransport':OFF,
    'step':ON,
    'stepSenseAdj':OFF,
    'stressExtList':['.odb', '.sim', '.SMAManifest'],
    'subGen':OFF,
    'subGenLibs':[],
    'subGenResidual':OFF,
    'subGenTypes':[],
    'submodel':OFF,
    'substrLibDefs':OFF,
    'substructure':OFF,
    'symmetricModelGeneration':OFF,
    'tempNoInterpolExtList':['.fil', '.odb', '.sim', '.SMAManifest'],
    'thermal':OFF,
    'tmpdir':'/tmp/nguyenb5/19926870',
    'tracer':OFF,
    'transientSensitivity':OFF,
    'unfold_param':OFF,
    'unsymm':OFF,
    'user':'code_binh.f90',
    'verbose':2,
    'visco':OFF,
    'xplSelect':OFF,
}
analysis = ExplicitAnalysis(options)
status = analysis.run()
sys.exit(status)
